# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.loader.efi.efiSysMountPoint = "/efi";
  boot.initrd.luks.devices.cryptroot.device =
    "/dev/disk/by-uuid/9861a123-4502-4c63-9b21-507d36fe542c";
  boot.initrd.availableKernelModules = [
    "vmd"
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0a423eb1-52e6-406f-9eaf-de3efd50622c";
    fsType = "btrfs";
    options = [
      "defaults"
      "compress=zstd"
      "subvol=root"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/0a423eb1-52e6-406f-9eaf-de3efd50622c";
    fsType = "btrfs";
    options = [
      "defaults"
      "compress=zstd"
      "subvol=home"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/0a423eb1-52e6-406f-9eaf-de3efd50622c";
    fsType = "btrfs";
    options = [
      "defaults"
      "compress=zstd"
      "subvol=nix"
    ];
  };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/4DCF-01DC";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/e7df7078-b56f-4135-bfe7-530ca8617fc0";
    fsType = "ext4";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/b1533042-571d-4b28-a967-6a8a0c713d46"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
